# Generated by Django 3.2.8 on 2021-10-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_message_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_events.sports_event')),
            ],
        ),
    ]
