# Generated by Django 3.2.8 on 2021-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports_event',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sports_event',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
